name: nodejs-template

on:
  push:
    # 只有推送到 master 分支才会触发
    branches:
      - unknown

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Commit and push if changed
        run: |-
          echo "hello world"
